#!/bin/bash
curl -X POST \
    http://localhost:8000/block \
    -H "Content-Type: application/json" \
    -H 'cache-control: no-cache' \
    -d '{"address":"14sW3HAjFBZfNEbphLoWqVNyZetrW8f19R", "star": {"dec": "68.434252", "ra": "16.56564", "story": "I also found a star using https://www.google.com/sky/"
        } }'
