#!/bin/bash
SIGNATURE=$1
curl -X POST \
http://localhost:8000/validate \
-H "Content-Type: application/json" \
-H 'cache-control: no-cache' \
-d '{"address":"14sW3HAjFBZfNEbphLoWqVNyZetrW8f19R","signature":"H3yxoXCH1OtNd1+h0c3bxmseoib0WUKicqaJYbCSU2zVLdJ78kPbF+OiQdOjg7ANxTzeBAxtdRaV3Ya92NScaI4="}'
