#!/bin/bash
SIGNATURE=$1
curl -X POST \
http://localhost:8000/validate \
-H "Content-Type: application/json" \
-H 'cache-control: no-cache' \
-d '{"address":"1G2qu3LAFUDWzapwy1fMp2FYo6yLpvWe1o","signature":"IDJea2rcDQtSSZUm/wieh8eE7kI+i/9J0WLoEIMyVXK+cyc+HOw3JBtEXiPl9aYZJIxocouM9ZI1LTHicGJ/cto="}'
